---
- hosts: all
  become: true
  tasks:
        - name: actualizando la cache de apt
          apt: update_cache=yes

        - name: Installing netdata to all machines
          apt: name={{ item }} update_cache=yes state=present
          with_items:
           - autoconf
           - autoconf-archive
           - autogen
           - automake
           - gcc
           - git
           - libmnl-dev
           - make
           - pkg-config
           - uuid-dev
           - zlib1g-dev
           - curl

        - name: "Clone repo"
          git:
            clone: yes
            update: yes
            repo: https://github.com/firehol/netdata.git
            dest: /usr/src/netdata

        - name: netdata installer
          shell: ./netdata-installer.sh --dont-wait --libs-are-really-here
          args:
            chdir: /usr/src/netdata/

        - name: Restarting netdata
          service:
            name: netdata
            state: restarted
