---
- apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install requeriments
  apt: name="{{ item }}"
  with_items:
    - git
    - php5.6
    - php5.6-dev
    - php5.6-mysql
    - php5.6-curl
    - php5.6-ldap
    - graphviz
    - apache2
    - aspell
    - php5.6-pspell
    - php5.6-gd
    - php5.6-xml
    - php5.6-xmlrpc
    - clamav
    - mysql-client
    - php-zip
    - php5.6-zip
    - python3-setuptools
    - python3
    - python-setuptools

- name: Restarting apache
  service:
    name: apache2
    state: restarted

- git:
    repo: git://git.moodle.org/moodle.git
    dest: /opt/moodle
    clone: yes
    force: yes

- name: Copying moodle
  command: cp -R /opt/moodle /var/www/html

- file:
    path: /var/www/moodledata
    state: directory
    owner: www-data
    mode: 0777

- file:
    path: /var/www/html/moodle
    state: directory
    owner: www-data
    mode: 0755

- name: Config Moodle
  template: src=config.php.j2 dest=/var/www/html/moodle/config.php

- name: Install pexpect for Ansible
  command: easy_install pexpect

- expect:
    command: ssh vagrant@192.168.80.2 "ip -4 addr show eth2 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'" > /tmp/iphaproxy.txt
    responses:
        (?i)re you sure you want to continue connecting (yes/no)?: "yes /n"
        (?i)password: "vagrant"

- expect:
    command: scp vagrant@192.168.80.2:/tmp/iphaproxy.txt /tmp/iphaproxy.txt
    responses:
        (?i)password: "vagrant"

- name: Read IP
  shell: cat /tmp/iphaproxy.txt
  register: IP

- replace:
    dest=/var/www/html/moodle/config.php
    regexp='192.168.8.186'
    replace='{{ IP.stdout }}'


- name: Restarting apache
  service:
    name: apache2
    state: restarted

- name: Restarting netdata
  service:
    name: netdata
    state: restarted
